export const appData = [
  {
    uid: "app",
    name: "MindZenx",
    date: "",
    url: "",
    bgImgURL: "1iwdcIovbviiaydPc0Hyf57h8ltlBiSoa",
  },
  {
    uid: "app",
    name: "Audiozic",
    date: "",
    url: "",
    bgImgURL: "1bkoKtagTw19OHO2ZEXPE4UMjptT06wde",
  },
  {
    uid: "app",
    name: "Collab",
    date: "",
    url: "",
    bgImgURL: "1Q6iRZRknM1Mr37tNTe-nz6qd0iHSgCh5",
  },
  {
    uid: "app",
    name: "Setting UI",
    date: "",
    url: "",
    bgImgURL: "1W6qyiPM-Glw0kVw_Dw6mn02trABspDzK",
  },
  {
    uid: "app",
    name: "Instagram profile",
    date: "",
    url: "",
    bgImgURL: "15p6LkdocMhfBBjyJivhemkW7SyoOfFch",
  },
  {
    uid: "app",
    name: "Ice Heaven",
    date: "",
    url: "",
    bgImgURL: "1ES1hjP0v_MGKQ4OFwPFr85ivWQ7C6Tsy",
  },

  { 
    uid: "app",
    name: "Chilling",
    date: "",
    url: "",
    bgImgURL: "1P3OVPs39OBv6DAHnj32tGrQipwwuLem0",
  },
  {
    uid: "app",
    name: "SignIN, SignUP",
    date: "",
    url: "",
    bgImgURL: "1I_RcHqIxhvar-j2um4CnZmBeWvJXCHbM",
  },
  {
    uid: "app",
    name: "Navigation UI",
    date: "",
    url: "",
    bgImgURL: "1RH3NyLAyDdDmnhx9zg5WumA4ki5BFYpA",
  },
  {
    uid: "app",
    name: "Movies app UI",
    date: "",
    url: "",
    bgImgURL: "1nXN3jhC1goDu8PvqzDHyUaSLWVrwP7d3",
  },
  {
    uid: "app",
    name: "Apple store",
    date: "",
    url: "",
    bgImgURL: "1hB3m3czy7l3taGNJmWDhFo8TXQwIIZep",
  },
  {
    uid: "app",
    name: "Music app UI",
    date: "",
    url: "",
    bgImgURL: "14qdrQjr2vKm-MTopOY_szCEj6fLYgeQ4",
  },
  {
    uid: "app",
    name: "calculor UI",
    date: "",
    url: "",
    bgImgURL: "1yT6ljnQKSoAIaWZw4UDu_GebPbpBg_N9",
  },
];
