export const webDevData =[
    {
        uid: "webDev",
        name: "MindZenx",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Resume Builder",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      
      {
        uid: "webDev",
        name: "M Sahil Hussain",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "reels Clone",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Movies App",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Static Web Page",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Todo List",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Harshoots",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Typing Game webDev",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
      {
        uid: "webDev",
        name: "Old Portfolio",
        date: "",
        url: "",
        bgImgURL: "15Be4L-7Gtqwypo4MwEMF8uKsrB7XH6vX",
      },
]