export const photoData = [
  { uid: "1", imageURl: "1-rw9SQfU5aNyxDZK75gJ3WYN2pwStckp", desc: "hello every one " },
  { uid: "2", imageURl: "1x5xt3I11QsvX5oNMbtgrncBbo7Y2Jd2N", desc: "hello every one " },
  { uid: "3", imageURl: "1GxsJfDipsSL3LgBnQFUCWWKhguZd4zAN", desc: "hello every one " },
  { uid: "4", imageURl: "16cXhyZ7D0_ez_e7e0aPOj7kkecP7zBF6", desc: "hello every one " },
  { uid: "5", imageURl: "1HUPgASKgorPyvekBvzV0nHQO8nb0HhKJ", desc: "hello every one " },
  { uid: "6", imageURl: "11A5j5YOvwkAtRuc-nGcSO6JHsBWExFe3", desc: "hello every one " },
  { uid: "7", imageURl: "1MG74U3LbKYfDvbv9fIOsJCSv-7GMifbL", desc: "hello every one " },
  { uid: "8", imageURl: "1jCqb8Ti7GMBh5pKxCeNl--MXifPbkxyY", desc: "hello every one " },
  { uid: "9", imageURl: "16tEp_aA5kwnng54REwaofg6vAhHGmiU4", desc: "hello every one " },
  { uid: "10", imageURl: "1oH6uYJjGp_Brl6poqZx7yl_scPyXppqE", desc: "hello every one " },
  { uid: "11", imageURl: "17uSOu_v3kVlI4dBd-fsJUpY2grbvebdi", desc: "hello every one " },
  { uid: "12", imageURl: "1elbNAS9H-n1DRHpzhe3bGwtKjeAhc-uw", desc: "hello every one " },
  { uid: "13", imageURl: "1OAd45EcFO4w2dXMHBzzUC3HbPJogMjBo", desc: "hello every one " },
  { uid: "14", imageURl: "1MXILU0eFhWuVM6zSScCBCFkpraERgt_1", desc: "hello every one " },
  { uid: "15", imageURl: "1aHnvb61gBmNnSPyzi3fP_V306EZbD1bg", desc: "hello every one " },
  { uid: "16", imageURl: "", desc: "" },
  { uid: "17", imageURl: "", desc: "" },
  { uid: "18", imageURl: "", desc: "" },
  { uid: "19", imageURl: "", desc: "" },
  { uid: "20", imageURl: "", desc: "" },
  { uid: "21", imageURl: "", desc: "" },
  { uid: "22", imageURl: "", desc: "" },
  { uid: "23", imageURl: "", desc: "" },
  { uid: "24", imageURl: "", desc: "" },
  { uid: "25", imageURl: "", desc: "" },
  { uid: "26", imageURl: "", desc: "" },
];
